[0m12:41:49.843382 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5ec3c2cad0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5ec3d46810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5ec3fd0a70>]}


============================== 12:41:49.851045 | 1d9f8f3f-4649-404d-90b6-c8b628c30933 ==============================
[0m12:41:49.851045 [info ] [MainThread]: Running with dbt=1.7.10
[0m12:41:49.851885 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/home/gitpod/.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt init crossborder_sql', 'send_anonymous_usage_stats': 'True'}
[0m12:41:49.852632 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': PosixPath('/home/gitpod/.dbt')}
[0m12:41:49.853228 [info ] [MainThread]: Creating dbt configuration folder at 
[0m12:41:49.854384 [debug] [MainThread]: Starter project path: /workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dbt/include/starter_project
[0m12:41:49.857606 [info ] [MainThread]: 
Your new dbt project "crossborder_sql" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m12:41:49.858244 [info ] [MainThread]: Setting up your profile.
[0m12:41:59.617357 [error] [MainThread]: Encountered an error:

[0m12:41:59.621017 [error] [MainThread]: Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dbt/cli/requires.py", line 91, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dbt/cli/requires.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dbt/cli/main.py", line 515, in init
    results = task.run()
              ^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dbt/task/init.py", line 344, in run
    self.setup_profile(profile_name)
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dbt/task/init.py", line 264, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dbt/task/init.py", line 181, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dbt/task/init.py", line 165, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/dbt/task/init.py", line 131, in generate_target_from_input
    target[key] = click.prompt(
                  ^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/click/termui.py", line 164, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.12/site-packages/click/termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m12:41:59.623710 [debug] [MainThread]: Resource report: {"command_name": "init", "command_wall_clock_time": 9.783747, "process_user_time": 2.634841, "process_kernel_time": 0.140364, "process_mem_max_rss": "108464", "process_in_blocks": "31432", "process_out_blocks": "80", "command_success": false}
[0m12:41:59.625037 [debug] [MainThread]: Command `dbt init` failed at 12:41:59.624700 after 9.79 seconds
[0m12:41:59.626044 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5ec3e34560>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5ec2e4f770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5ec2c6f4a0>]}
[0m12:41:59.627103 [debug] [MainThread]: Flushing usage events
[0m12:50:36.505619 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd45c69cb30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd45c8f6300>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd45c69ccb0>]}


============================== 12:50:36.510402 | f2d3a911-f3f6-4c8d-bea9-3bf3b3603e9d ==============================
[0m12:50:36.510402 [info ] [MainThread]: Running with dbt=1.7.10
[0m12:50:36.511250 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '/home/gitpod/.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init crossborder_sql', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:50:36.512450 [info ] [MainThread]: A project called crossborder_sql already exists here.
[0m12:50:36.513563 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 0.011250239, "process_user_time": 2.502316, "process_kernel_time": 0.135691, "process_mem_max_rss": "92360", "process_in_blocks": "24080", "process_out_blocks": "8"}
[0m12:50:36.514393 [debug] [MainThread]: Command `dbt init` succeeded at 12:50:36.514168 after 0.01 seconds
[0m12:50:36.515033 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd46047bdd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd45e0516a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fd45c7b4230>]}
[0m12:50:36.515688 [debug] [MainThread]: Flushing usage events
[0m12:51:02.521241 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1b1f3a0a70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1b1f484b90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1b1f5e8b60>]}


============================== 12:51:02.529796 | 0fb73640-f36e-45d8-bcaa-8f2dfb68dd87 ==============================
[0m12:51:02.529796 [info ] [MainThread]: Running with dbt=1.7.10
[0m12:51:02.531226 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/gitpod/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m12:51:02.532756 [info ] [MainThread]: dbt version: 1.7.10
[0m12:51:02.533841 [info ] [MainThread]: python version: 3.12.2
[0m12:51:02.534878 [info ] [MainThread]: python path: /home/gitpod/.pyenv/versions/3.12.2/bin/python3.12
[0m12:51:02.535918 [info ] [MainThread]: os info: Linux-6.1.75-060175-generic-x86_64-with-glibc2.35
[0m12:51:02.537053 [info ] [MainThread]: Using profiles dir at /home/gitpod/.dbt
[0m12:51:02.538116 [info ] [MainThread]: Using profiles.yml file at /home/gitpod/.dbt/profiles.yml
[0m12:51:02.539029 [info ] [MainThread]: Using dbt_project.yml file at /workspace/crossborder_project/dbt_project.yml
[0m12:51:02.539830 [info ] [MainThread]: Configuration:
[0m12:51:02.540862 [info ] [MainThread]:   profiles.yml file [[31mERROR not found[0m]
[0m12:51:02.541805 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m12:51:02.542690 [info ] [MainThread]: Required dependencies:
[0m12:51:02.543665 [debug] [MainThread]: Executing "git --help"
[0m12:51:02.547871 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--config-env=<name>=<envvar>] <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m12:51:02.549054 [debug] [MainThread]: STDERR: "b''"
[0m12:51:02.550047 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m12:51:02.551019 [info ] [MainThread]: Connection test skipped since no profile was found
[0m12:51:02.552150 [info ] [MainThread]: [31m2 checks failed:[0m
[0m12:51:02.553270 [info ] [MainThread]: dbt looked for a profiles.yml file in /home/gitpod/.dbt/profiles.yml, but did
not find one. For more information on configuring your profile, consult the
documentation:

https://docs.getdbt.com/docs/configure-your-profile


[0m12:51:02.554388 [info ] [MainThread]: Project loading failed for the following reason:
 project path </workspace/crossborder_project/dbt_project.yml> not found

[0m12:51:02.556237 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_wall_clock_time": 0.04061616, "process_user_time": 2.862227, "process_kernel_time": 0.196152, "process_mem_max_rss": "92172", "process_in_blocks": "11896", "process_out_blocks": "24", "command_success": false}
[0m12:51:02.557589 [debug] [MainThread]: Command `dbt debug` failed at 12:51:02.557215 after 0.04 seconds
[0m12:51:02.558693 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1b1f5ebd70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1b1f60c950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1b1f60f9e0>]}
[0m12:51:02.559823 [debug] [MainThread]: Flushing usage events
